# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits:
#   $(arg ur5e_prefix)shoulder_pan_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
#   $(arg ur5e_prefix)shoulder_lift_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
#   $(arg ur5e_prefix)elbow_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
#   $(arg ur5e_prefix)wrist_1_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
#   $(arg ur5e_prefix)wrist_2_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
#   $(arg ur5e_prefix)wrist_3_joint:
#     has_velocity_limits: true
#     max_velocity: 1.50
#     has_acceleration_limits: true
#     max_acceleration: 2.0
  # $(arg ur5e_prefix)gripper_finger_joint:
  #   has_velocity_limits: true
  #   max_velocity: 1.50
  #   has_acceleration_limits: true
  #   max_acceleration: 2.0

joint_limits:
  $(arg ur5e_prefix)elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: True
    max_acceleration: 12.8
  $(arg ur5e_prefix)shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 3.2
  $(arg ur5e_prefix)shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 3.2
  $(arg ur5e_prefix)wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.2
  $(arg ur5e_prefix)wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.2
  $(arg ur5e_prefix)wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.2

# joint_limits:
#   elbow_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0
#   finger_joint:
#     has_velocity_limits: true
#     max_velocity: 2
#     has_acceleration_limits: false
#     max_acceleration: 0
#   shoulder_lift_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0
#   shoulder_pan_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_1_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_2_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_3_joint:
#     has_velocity_limits: true
#     max_velocity: 3.141592653589793
#     has_acceleration_limits: false
#     max_acceleration: 0