controller_list:
  # - name: gripper_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: True
  #   joints:
  #     - finger_joint
  - name: scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - $(arg ur5e_prefix)shoulder_pan_joint
      - $(arg ur5e_prefix)shoulder_lift_joint
      - $(arg ur5e_prefix)elbow_joint
      - $(arg ur5e_prefix)wrist_1_joint
      - $(arg ur5e_prefix)wrist_2_joint
      - $(arg ur5e_prefix)wrist_3_joint